### ISSUE TITLE
The paper and the code implementation are different

### ISSUE THREAD

**Issue by Love-syntacticSugar** [mkang315/ASF-YOLO#17]
Did you replace the Gaussian kernel in the paper with conv2d directly?
![image](https://github.com/user-attachments/assets/d208e63d-da96-492b-9cc9-d6e2e81a6ea6)

**Comment by Love-syntacticSugar** [comment]
Or is the realization of Gaussian kernel achieved through convolution kernel?

**Comment by mkang315** [comment]
The nearest neighbor interpolation method is used to align all feature maps to the same resolution as the P3, which was stated in the text below the paragraph in your screenshot. Thanks!
