### ISSUE TITLE
two questions 

### ISSUE THREAD

**Issue by HbutLbh** [mkang315/ASF-YOLO#6]
when i use yolov5l-seg.pt.it appears Transferred 602/671 items from yolov5l-seg.pt.maybe  it cannoy apply all items
secend ,when i training ,it apeears AttributeError:   anchors, shape = self.anchors[i], p[i].shape,'list' object has no attribute 'shape'
hope get you reply

**Comment by Williamwsk** [comment]
> when i use yolov5l-seg.pt.it appears Transferred 602/671 items from yolov5l-seg.pt.maybe it cannoy apply all items secend ,when i training ,it apeears AttributeError: anchors, shape = self.anchors[i], p[i].shape,'list' object has no attribute 'shape' hope get you reply

Have you solved this problem?
